---

include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - .gitlab-ci_common.yaml
      - template/automagic.gitlab-ci.yaml


variables:
    MY_PROJECT_ID: "38927651"

Documentation.Lint:
  rules:
    - when: never

Documentation.Build:
  rules:
    - when: never

pages:
  rules:
    - when: never

Update Sub Repo:
  extends: .submodule_update_trigger
  parallel:
    matrix:
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/ops
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/infrastructure/website
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/ansible_playbooks
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/ansible-roles
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/ansible_docker_os
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/ansible_test
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/common
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/docker_management
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/execution_environment
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/firewall
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/git_configuration
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/homeassistant
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/kubernetes
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/nfc_glpi
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/django_template
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/docker-bind
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/docker-mail
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/docker-buildx-qemu
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/docker-glpi
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/gitlab-ci
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/infrastructure/configuration-management/itil_runbooks
      - SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/kubernetes_monitoring
