---

name: Pull Requests


on:
  pull_request: {}


jobs:

  conventional-commits:
    name: Conventional Commit Checks
    uses: nofusscomputing/github-ci/.github/workflows/pull-requests.yaml@genesis
