name: pcu


on:
  push:
    branches:
      - '**'
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch:
  workflow_call:

jobs:

  refreshDepsProd:
    runs-on: ubuntu-latest
    steps:

      - uses: zehengl/refresh-python-dependency@v0.4.2
        with:
          path: requirements-production.txt


  refreshDeps:
    runs-on: ubuntu-latest
    steps:


      - uses: zehengl/refresh-python-dependency@v0.4.2
        with:
          path: requirements.txt
