---

name: 'Process Unit Test Artifact'

on:
  workflow_run:
    workflows:
      - 'Unit Test'
    types:
      - completed


permissions:
  contents: read
  actions: read
  checks: write


jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:

      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          artifact: unit-test-results-${{ matrix.python-version }}
          badge-title: 'Unit Tests [Python ${{ matrix.python-version }}]'
          name: Unit Test Report [Python ${{ matrix.python-version }}]
          path: '*.xml'
          reporter: java-junit
