# This gitlab-ci file is used for creating docker images.
# by including this file, the jobs will be autocreated.

include:
  - local: $JOB_ROOT_DIR/.gitlab-ci_common.yaml
  - local: $JOB_ROOT_DIR/lint/ansible.gitlab-ci.yaml
  - local: $JOB_ROOT_DIR/conventional_commits/.gitlab-ci.yml
  - local: $JOB_ROOT_DIR/git_push_mirror/.gitlab-ci.yml
  - local: $JOB_ROOT_DIR/gitlab_release/.gitlab-ci.yml


Ansible Lint (python 3.11):
  variables:
    ANSIBLE_LINT_PATH: defaults/ handlers/ meta/ tasks/ templates/
  extends:
    - .ansible_linter_defaults
  image: python:3.11-slim
  resource_group: build
  needs: []


Gitlab Release:
  extends:
    - .gitlab_release


Github (Push --mirror):
  extends:
    - .git_push_mirror