# This gitlab-ci file is used for the autocreation of ci jobs.
# by including this file, the jobs will be autocreated if they are detected as required.

variables:
  NFC_AUTO_JOBS: 'true'

include:
  - local: $JOB_ROOT_DIR/.gitlab-ci_common.yaml

    # Chore
  - local: $JOB_ROOT_DIR/automation/.gitlab-ci-ansible.yaml

    # Validation
  - local: $JOB_ROOT_DIR/lint/ansible.gitlab-ci.yaml
  - local: $JOB_ROOT_DIR/conventional_commits/.gitlab-ci.yml

    # sync
  - local: $JOB_ROOT_DIR/git_push_mirror/.gitlab-ci.yml

    # release
  - local: $JOB_ROOT_DIR/gitlab_release/.gitlab-ci.yml

    # templates
  - local: $JOB_ROOT_DIR/template/ansible-role.gitlab-ci.yaml
  - local: $JOB_ROOT_DIR/template/docker-image.gitlab-ci.yaml
  - local: $JOB_ROOT_DIR/template/mkdocs-documentation.gitlab-ci.yaml


#
# Chores
#
Update Git Submodules:
  extends: .ansible_playbook_git_submodule

Search Issues for git patches:
  extends: .ansible_playbook_mr_from_issue_comment_patch

#
# Release
#
Gitlab Release:
  extends:
    - .gitlab_release


#
# Sync
#
Github (Push --mirror):
  extends:
    - .git_push_mirror
  needs: []
