variables:
    JOB_ROOT_DIR: 'gitlab-ci'
    GIT_SUBMODULE_STRATEGY: normal
    #PIPELINE_RUN_TRIGGER: 'false'
    PIPELINE_RUN_SCHEDULE: 'true'

stages:
    - chores
    - validation
    - build
    - prepare
    - test
    - release
    - sync
    - deploy
    - publish
