---

name: 'Build Development Image'


on:
  # workflow_call:
  #   inputs:
  #     build-branch:         # tag / dev
  #       required: true
  #       type: string
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      # - '!master'
  # pull_request:
  #     branches: [ "development" ]
env:
  DOCKER_BUILD_IMAGE: "ghcr.io/${{ github.repository }}:${{ github.sha }}"

jobs:

  docker-build:
    runs-on: ubuntu-latest
    name: Build Current Commit
    steps:


      - uses: actions/checkout@v4


      - name: Log into registry ghcr.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Setup BuildX
        run: |
          docker buildx create --name project-v3-builder;
          docker buildx use project-v3-builder;


      - name: build image
        run: |
          docker buildx build --platform="linux/amd64,linux/arm64" . \
            --label "org.opencontainers.image.created=$(date '+%Y-%m-%dT%H:%M:%S%:z')" \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.revision=${{ github.sha }}" \
            \
            --label "io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository }}/development/README.md" \
            --label 'io.artifacthub.package.maintainers=[{"name":"No Fuss Computing","email":"helpdesk@nofusscomputing.com"}]' \
            \
            --annotation "org.opencontainers.image.description=a DESCRIPTION for multi-arch images" \
            --annotation "org.opencontainers.image.created=$(date '+%Y-%m-%dT%H:%M:%S%:z')" \
            --annotation "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --annotation "org.opencontainers.image.revision=${{ github.sha }}" \
          --push \
          --file dockerfile \
          --tag ghcr.io/${{ github.repository }}:${{ github.sha }};


      - name: Remove "Unknown" Image from Manifest
        run: |

          DOCKER_MULTI_ARCH_IMAGES=$(docker buildx imagetools inspect "$DOCKER_BUILD_IMAGE" --format "{{ range .Manifest.Manifests }}{{ if ne (print .Platform) \"&{unknown unknown  [] }\" }}$DOCKER_BUILD_IMAGE@{{ println .Digest }}{{end}} {{end}}");

          # if [ "${{ inputs.build-branch }}" == "dev" ]; then

          #   docker buildx imagetools create $DOCKER_MULTI_ARCH_IMAGES \
          #     --tag ghcr.io/${{ github.repository }}:${{ github.sha }} \
          #     --tag ghcr.io/${{ github.repository }}:dev;

          # elif [ "${{ inputs.build-branch }}" == "tag" ]; then

          #   docker buildx imagetools create $DOCKER_MULTI_ARCH_IMAGES \
          #     --tag ghcr.io/${{ github.repository }}:${{ github.sha }} \
          #     --tag ghcr.io/${{ github.repository }}:${{ github.ref_name }} \
          #     --tag ghcr.io/${{ github.repository }}:latest;

          # fi;

          docker buildx imagetools create $DOCKER_MULTI_ARCH_IMAGES \
            --tag ${{ env.DOCKER_BUILD_IMAGE }} \
            --tag ghcr.io/${{ github.repository }}:dev;


      - name: Cleanup BuildX
        run: |
          docker buildx rm project-v3-builder;


  docker-scan:
    needs: docker-build
    runs-on: ubuntu-latest
    name: Build Current Commit
    steps:


      - uses: actions/checkout@v4


      - name: Log into registry ghcr.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: '${{ env.DOCKER_BUILD_IMAGE }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'