---

name: Build Development Image


on:
  push:
    branches:
      - development


jobs:

  docker-build:
    runs-on: ubuntu-latest
    name: Build Current Commit
    steps:


      - uses: actions/checkout@v2


      - name: Log into registry ghcr.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: build image
        run: |
          docker buildx create --name project-v3-builder;

	        docker buildx use project-v3-builder;

          docker buildx build --platform="linux/amd64,linux/arm64" . \
            --label org.opencontainers.image.created="$(date '+%Y-%m-%dT%H:%M:%S%:z')" \
            --label org.opencontainers.image.source="${{ github.server.url }}/${{ github.repository }}" \
            --label org.opencontainers.image.revision="${{ github.sha }}" \
            --label io.artifacthub.package.readme-url="https://raw.githubusercontent.com/${{ github.repository }}/development/README.md" \
            --label io.artifacthub.package.maintainers='[{"name":"No Fuss Computing","email":"helpdesk@nofusscomputing.com"}]' \
          --push \
          --file dockerfile \
          --tag ghcr.io/${{ github.repository }}:dev \
          --tag ghcr.io/${{ github.repository }}:${{ github.sha }};

          docker buildx rm project-v3-builder;
