---

name: 'Bump'


on:
  workflow_dispatch:
    inputs:
      CZ_PRE_RELEASE:
        default: none
        required: false
        description: Create Pre-Release {alpha,beta,rc,none}
      CZ_INCREMENT:
        default: none
        required: false
        description: Type of increment to conduct {MAJOR,MINOR,PATCH,none}
  # workflow_call:
  #   inputs:
  #     CZ_PRE_RELEASE:
  #       default: none
  #       required: false
  #       description: Create Pre-Release {alpha,beta,rc,none}
  #       type: string
  #     CZ_INCREMENT:
  #       default: none
  #       required: false
  #       description: Type of increment to conduct {MAJOR,MINOR,PATCH,none}
  #       type: string
  #   secrets:
  #     WORKFLOW_TOKEN:
  #       description: Token used to create the tag (required to trigger 'tag' workflow)
  #       required: true
  # push:
  #   branches:
  #     - '**'
  #   tags:
  #     - '*'



jobs:

  bump:
    name: 'Bump'
    uses: nofusscomputing/github-ci/.github/workflows/bump.yaml@genesis
    secrets:
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
    