---

# name: 'CI'


on:
  # workflow_call:
  #   inputs:
  #     build-branch:         # tag / dev
  #       required: true
  #       type: string
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches:
      - '**'


# env:
#   DOCKER_BUILD_IMAGE: "ghcr.io/${{ github.repository }}-fred:${{ github.sha }}"


# permissions:
#   pull-requests: write
#   contents: read
#   actions: read
#   checks: write
#   packages: write
#   security-events: write
#   statuses: write



jobs:

  docker:
    name: 'Docker'
    uses: nofusscomputing/scratchpad/.github/workflows/docker.yaml@further-testing
    with:
      DOCKER_BUILD_IMAGE_NAME: "${{ github.repository }}"
