---

name: 'CI'


on:
  # workflow_call:
  #   inputs:
  #     build-branch:         # tag / dev
  #       required: true
  #       type: string
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      # - '!master'
  pull_request:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
  #     branches: [ "development" ]
env:
  DOCKER_BUILD_IMAGE: "ghcr.io/${{ github.repository }}:${{ github.sha }}"


permissions:
  pull-requests: write
  contents: read
  actions: read
  checks: write
  packages: write
  security-events: write
  statuses: write



jobs:

  docker:
    name: 'Docker'
    uses: nofusscomputing/scratchpad/.github/workflows/docker/docker.yaml@further-testing