---

name: 'CI'


on:
  push:
    branches:
      - '**'
    tags:
      - '*'


jobs:


  docker:
    if:
      (${{
        github.event.push
          ||
        github.ref_type == 'tag'
      }})
    name: 'Docker'
    # needs:
    #   - python
    uses: nofusscomputing/github-ci/.github/workflows/docker.yaml@genesis
    with:
      DOCKER_BUILD_IMAGE_NAME: "${{ github.repository }}"
      DOCKER_PUBLISH_REGISTRY: "ghcr.io"
      DOCKER_PUBLISH_IMAGE_NAME: "nofusscomputing/image-publish"
    secrets:
      DOCKER_PUBLISH_USERNAME: ${{ github.actor }}
      DOCKER_PUBLISH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}


  # test:
  #   name: 'Unit Tests'
  #   # needs:
  #   #   - python
  #   uses: nofusscomputing/github-ci/.github/workflows/unit-test.yaml@genesis




##################################################################################


  # python:
  #   name: 'Python'
  #   uses: ./.github/workflows/python.yaml
  #   # with:
  #   #   DOCKER_BUILD_IMAGE_NAME: "${{ github.repository }}"
  #   #   DOCKER_PUBLISH_REGISTRY: "ghcr.io"
  #   #   DOCKER_PUBLISH_IMAGE_NAME: "nofusscomputing/image-publish"


  # django:
  #   name: 'Django'
  #   uses: ./.github/workflows/unit-test.yaml
  #   # with:
  #   #   DOCKER_BUILD_IMAGE_NAME: "${{ github.repository }}"
  #   #   DOCKER_PUBLISH_REGISTRY: "ghcr.io"
  #   #   DOCKER_PUBLISH_IMAGE_NAME: "nofusscomputing/image-publish"


  # docker:
  #   name: 'Docker'
  #   # needs:
  #   #   - python
  #   uses: ./.github/workflows/docker.yaml
  #   with:
  #     DOCKER_BUILD_IMAGE_NAME: "${{ github.repository }}"
  #     DOCKER_PUBLISH_REGISTRY: "docker.io"
  #     DOCKER_PUBLISH_IMAGE_NAME: "nofusscomputing/centurion-erp"


  # release:
  #   name: 'Release'
  #   uses: ./.github/workflows/release.yaml
  #   # with:
  #   #   DOCKER_BUILD_IMAGE_NAME: "${{ github.repository }}"
