---
name: 'CI'


on:
  push:
    branches:
      - '**'
    tags:
      - '*'

  pull_request:
    

jobs:

  mkdocs:
    name: 'MKDocs'
    uses: nofusscomputing/action_mkdocs/.github/workflows/reusable_mkdocs.yaml@genesis
    # secrets:
    #   WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
