# ---
# name: 'Python'


# on:
#   push:

# jobs:

#   collection:
#     name: 'Ansible Collection'
#     uses: nofusscomputing/action_ansible_collection/.github/workflows/reusable_ansible_collection.yaml@genesis
#     # secrets:
#     #   WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
