---

name: Project


on:
  issues:
    types:
      - opened
      - reopened
      - transferred
      - milestoned
      - demilestoned
      - closed
      - assigned
  pull_request: 
    types:
      - opened
      - edited
      - reopened
      - closed



jobs:


  project:
    name: Project
    uses: nofusscomputing/action_project/.github/workflows/project.yaml@genesis
    with:
      PROJECT_URL: https://github.com/orgs/nofusscomputing/projects/7
    secrets:
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
