---

name: Project


on:
  issues:
    types:
      - opened
      - reopened
      - transferred
      - labeled
      - milestoned
      - demilestoned
      - closed
      - assigned
  pull_request: 
    types:
      - opened
      - reopened
      - labeled



env:
  PROJECT_URL: https://github.com/orgs/nofusscomputing/projects/7


jobs:


  # project-add:
  #   name: Add
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Add To Project
  #       run: |
  #         echo todo;

  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:

      - name: Add To Project
        run: |
          echo "Debug github.event_name=${{ github.event_name }}";
          echo "Debug github.event.action=${{ github.event.action }}";


  project-add:
    name: Add
    runs-on: ubuntu-latest
    steps:

      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e    # v1.0.2
        with:
          project-url: ${{ env.PROJECT_URL }}
          github-token: ${{ secrets.WORKFLOW_TOKEN }}



  project-remove:
    name: Remove
    if: ${{(
        github.event_name == 'issues' && github.event.action == 'transferred'
      )}}
    runs-on: ubuntu-latest
    steps:

      - name: Remove From Project
        run: |
          echo todo;



  project-fields:
    name: Field Values
    if: ${{(
        github.event_name == 'issues' && github.event.action != 'transferred'
      )}}
    needs:
      - project-add
    runs-on: ubuntu-latest
    outputs:
      project-start-date:  ${{ steps.start-date.outputs.values }}
      project-end-date:  ${{ steps.end-date.outputs.values }}
      project-status:  ${{ steps.status.outputs.values }}
    steps:


      - name: Fetch Start Date
        uses: EndBug/project-fields@v2
        id: start-date
        with:
          operation: get
          fields: Start date
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          project_url: ${{ env.PROJECT_URL }}


      - name: Fetch End Date
        uses: EndBug/project-fields@v2
        id: end-date
        with:
          operation: get
          fields: End date
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          project_url: ${{ env.PROJECT_URL }}


      - name: Fetch Status
        uses: EndBug/project-fields@v2
        id: status
        with:
          operation: get
          fields: Status
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          project_url: ${{ env.PROJECT_URL }}



  project-set-start-date:
    name: Set Start Date
    if: ${{(
        github.event_name == 'issues' && github.event.action == 'assigned'
      )}}
    needs:
      - project-fields
    runs-on: ubuntu-latest
    steps:

      - name: Set Start Date
        run: |
          echo todo;


  
  project-set-status:
    name: Set Status
    if: ${{ needs.project_fields.project-status != 'Awaiting Feedback' }}
    needs:
      - project-fields
    runs-on: ubuntu-latest
    steps:


      - name: Set Status Planning
        if: ${{ github.event_name == 'issues' && github.event.action == 'milestoned' }}
        uses: EndBug/project-fields@v2
        with:
          operation: set
          fields: Status
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          project_url: ${{ env.PROJECT_URL }}
          values: 'Planning'


      - name: Set Status In Progress
        if: ${{ github.event_name == 'issues' && github.event.action == 'assigned' }}
        uses: EndBug/project-fields@v2
        with:
          operation: set
          fields: Status
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          project_url: ${{ env.PROJECT_URL }}
          values: 'In progress'


      - name: Set Status done
        if: ${{ github.event_name == 'issues' && github.event.action == 'closed' }}
        uses: EndBug/project-fields@v2
        with:
          operation: set
          fields: Status
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          project_url: ${{ env.PROJECT_URL }}
          values: 'Done'


      - name: Clear Status
        if: ${{(
            (
              (github.event_name == 'issues' && github.event.action == 'reopened')
                ||
              (github.event_name == 'issues' && github.event.action == 'demilestoned')
            ) 
            &&
            needs.project_fields.project-status == 'Ready to Commence'
          )}}
        uses: EndBug/project-fields@v2
        with:
          operation: clear
          fields: Status
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          project_url: ${{ env.PROJECT_URL }}



  project-set-end-date:
    name: Set End Date
    # if: issue closed or re-opened
    needs:
      - project-fields
    runs-on: ubuntu-latest
    steps:


      - name: Set End date
        if: ${{(
            github.event_name == 'issues' && github.event.action != 'closed'
          )}}
        run: |
          echo todo;


      - name: Clear End Date
        if: ${{(
            github.event_name == 'issues' && github.event.action != 'reopened'
          )}}
        uses: EndBug/project-fields@v2
        with:
          operation: clear
          fields: End date
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          project_url: ${{ env.PROJECT_URL }}
