---

name: Pull Requests


on:
  pull_request: {}


jobs:

  conventional-commits:
    name: Conventional Commit Checks
    uses: nofusscomputing/scratchpad/.github/workflows/pull-requests.yaml@development
