name: Release

on:
  workflow_call:
  # push:
  #   tags:
  #     - '*'


jobs:
  release:
    name: Release
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: Test
      #   # if: startsWith(github.ref, 'refs/tags/')
      #   run: echo ${{ github.sha }} > Release.txt

      # - name: Test
      #   # if: startsWith(github.ref, 'refs/tags/')
      #   run: cat Release.txt
      
      - name: Create GH Release
        if: ${{ github.ref_type == 'tag' }}
        id: release
        uses: softprops/action-gh-release@v2
        with:
          # files: |
          #   Release.txt
          #   LICENSE
          body: |
            # A title block

            Some release text

            A [link](https://nofusscomputing.com) does render as markdown works.




  manage-labels:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:

      # - uses: actions/checkout@v4

      - run: |
          mkdir -p .github
          cat <<EOF > .github/labels.yaml
          labels:
            ${{ github.ref_name }}:
              color: "EEEEEE"
              description: Relates to package metadata

          EOF;

      - uses: oliversalzburg/action-label-manager@v0.0.9
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      # - run: | # Use to create env var for use in uploading files
      #     echo "${{ steps.release.outputs.upload_url }}" > release-url.txt


      # - name: Upload Release URL
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: release-URL
      #     path: release-url.txt

