name: Release

on:
  workflow_call:
  # push:
  #   tags:
  #     - '*'

jobs:
  release:
    name: Release
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4

      - name: Test
        # if: startsWith(github.ref, 'refs/tags/')
        run: echo ${{ github.sha }} > Release.txt
      
      # - name: Test
      #   # if: startsWith(github.ref, 'refs/tags/')
      #   run: cat Release.txt
      
      - name: Create GH Release
        if: ${{ github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Release.txt
            LICENSE