name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4
      - name: Build
        # if: startsWith(github.ref, 'refs/tags/')
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        # if: startsWith(github.ref, 'refs/tags/')
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE